spring:
  profiles:
    active:
    - dev

-------------
spring:
    profiles: dev
    application:
          name: chtpro-config-haite-dev
------------
spring:
    profiles: test
    application:
     name: chtpro-config-haite-test
